-- MySQL Script generated by MySQL Workbench
-- Sun Dec 11 22:49:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema apptienda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema apptienda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apptienda` DEFAULT CHARACTER SET utf8 ;
USE `apptienda` ;

-- -----------------------------------------------------
-- Table `apptienda`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apptienda`.`factura` (
  `id` INT NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `id_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apptienda`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apptienda`.`ventas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `subtotal` INT NOT NULL,
  `factura_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ventas_factura_idx` (`factura_id` ASC) VISIBLE,
  CONSTRAINT `fk_ventas_factura`
    FOREIGN KEY (`factura_id`)
    REFERENCES `apptienda`.`factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
